AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWSQS::OpenShift::Manager resource type

Globals:
  Function:
    Timeout: 60  # docker start-up times can be long for SAM CLI

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: awsqs_openshift_manager.handlers.resource
      Runtime: python3.7
      CodeUri: build/

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: awsqs_openshift_manager.handlers.test_entrypoint
      Runtime: python3.7
      CodeUri: build/

  DebugTestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: awsqs_openshift_manager.handlers.ide_entrypoint
      Runtime: python3.7
      CodeUri: src/

